INSERT INTO timetable.course (code, name, hour, class, for_specialism, number_students, lectures)
VALUES('co112', 'hardware', '3', '1', 'none', 'medium', 'bschulle_dfg'),
('co120', 'programming', '5', '1', 'none', 'medium', 'ajf_tora'),
('co140', 'logic', '3', '1', 'none', 'medium', 'imh'),
('co145', 'mathematical_methods', '8', '1', 'none', 'medium', 'jb'),
('co142', 'discrete_mathematics', '3', '1', 'none', 'medium', 'svb'),
('co161', 'lab', 'lab', '1', 'none', 'medium', 'tora'),
('co220', 'software_engineering_design', '2', '2', 'none', 'medium', 'rbc'),
('co220', 'software_engineering_design_lab', 'lab', '2', 'none', 'medium', 'rbc'),
('co221', 'compilers', '5', '2', 'none', 'medium', 'nd_phjk'),
('co223', 'concurrency', '3', '2', 'none', 'medium', 'jk'),
('co240', 'models_of_computation', '3', '2', 'none', 'medium', 'pg'),
('co245', 'statistics', '3', '2', 'none', 'medium', 'simon'),
('co261', 'lab_two, lab', '2', 'none', 'medium', 'mjw03'),
('co276', 'introduction_to_prolog', '4', '2', 'none', 'medium', 'mjs'),
('co302', 'software_engineering_practice', '2', '3', 'optional', 'medium', 'rbc'),
('co312', 'advanced_databases', '4', '3', 'optional', 'small', 'pjm'),
('co382', 'type_systems_for_programming_languages', '4', '3', 'optional', 'small', 'svb'),
('co316', 'computer_vision', '4', '3', 'optional', 'medium', 'gzy_sl98'),
('co320', 'complex_systems', '4', '3', 'optional', 'medium', 'ae'),
('co337', 'simulation_and_modelling', '4', '3', 'optional', 'medium', 'ajf_jb'),
('co338', 'pervasive_computing', '4', '3', 'optional', 'medium', 'jamm'),
('co343', 'operations_research', '4', '3', 'optional', 'medium', 'gcasale'),
('co395', 'machine_learning', '4', '3', 'optional', 'medium', 'maja'),
('co395', 'machine_learning_lab', 'lab', '3', 'optional', 'medium', 'maja'),
()